<style>
   .list-group-item a{
       font-size: 20px;
       color: black;
    }
    </style>
<body>
<ul class="list-group">
<?php for($i=0; $i<count($policy); $i++): ?>

  <li class="list-group-item">  <a href="../webroot/index.php?controller=default&action=show&name=<?=$_GET['action']?>&id=<?=$policy[$i]->getid()?>" ><?=$policy[$i]->getName()?></a> <br>
  </li>
      <?php endfor; ?>
</ul>
<?php /*for($j=1; $j<=$GLOBALS['total']; $j++): */?><!--
<a href="../webroot/index.php?controller=default&action=<?/*=$_GET['action']*/?>&id=<?/*=$j*/?>"><button><?/*=$j*/?></button></a>
--><?php /*endfor;*/?>

<?php $j=1; $jl=$GLOBALS['total'];?>
<ul class="pagination"><li><a href="../webroot/index.php?controller=default&action=<?=$_GET['action']?>&id=<?=$j?>"><button><?=$j?></button></a></li>
    <li><a href="../webroot/index.php?controller=default&action=but&name=<?=$_GET['action']?>"><button>...</button></a></li>
   <li> <a href="../webroot/index.php?controller=default&action=<?=$_GET['action']?>&id=<?=$j?>"><button><?=$jl?></button></a></li>
</ul>
</body>